spring.application.name=ProductService

# H2 Database
spring.datasource.url=jdbc:h2:mem:productdb NON_KEYWORDS=PRODUCT
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.cors.allowed-origins=*
server.servlet.forward-extension-mappings=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# H2 Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# CORS for Angular
#spring.web.cors.allowed-origins=http://localhost:4200
server.port=8081



